// This file is auto-generated by @hey-api/openapi-ts

export const CommentSchemaSchema = {
    required: ['approved', 'author', 'contentKey', 'contentName', 'date', 'id', 'message', 'trashed'],
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        date: {
            type: 'string',
            format: 'date-time'
        },
        author: {
            type: 'string'
        },
        message: {
            type: 'string'
        },
        contentKey: {
            type: 'string',
            format: 'uuid'
        },
        contentName: {
            type: 'string'
        },
        approved: {
            type: 'boolean'
        },
        trashed: {
            type: 'boolean'
        },
        replyTo: {
            type: 'integer',
            format: 'int32',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const EventMessageTypeModelSchema = {
    enum: ['Default', 'Info', 'Error', 'Success', 'Warning'],
    type: 'string'
} as const;

export const NotificationHeaderModelSchema = {
    required: ['category', 'message', 'type'],
    type: 'object',
    properties: {
        message: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        type: {
            '$ref': '#/components/schemas/EventMessageTypeModel'
        }
    },
    additionalProperties: false
} as const;