// This file is auto-generated by @hey-api/openapi-ts

export type CommentSchema = {
    id: number;
    date: string;
    author: string;
    message: string;
    contentKey: string;
    contentName: string;
    approved: boolean;
    trashed: boolean;
    replyTo?: (number) | null;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export const EventMessageTypeModel = {
    DEFAULT: 'Default',
    INFO: 'Info',
    ERROR: 'Error',
    SUCCESS: 'Success',
    WARNING: 'Warning'
} as const;

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type GetCommentByIdData = {
    id: number;
};

export type GetCommentByIdResponse = ((CommentSchema));

export type PostCommentsData = {
    requestBody?: (CommentSchema);
};

export type PostCommentsResponse = (boolean);

export type GetCommentsResponse = (Array<(CommentSchema)>);

export type GetCommentsByContentkeyData = {
    contentkey: string;
};

export type GetCommentsByContentkeyResponse = (Array<(CommentSchema)>);

export type GetCommentsByContentkeyApprovedData = {
    contentkey: string;
};

export type GetCommentsByContentkeyApprovedResponse = (Array<(CommentSchema)>);

export type GetCommentsByContentkeyApprovedCountData = {
    contentkey: string;
};

export type GetCommentsByContentkeyApprovedCountResponse = (number);

export type GetCommentsByContentkeyCountData = {
    contentkey: string;
};

export type GetCommentsByContentkeyCountResponse = (number);

export type GetCommentsByContentkeyUnapprovedData = {
    contentkey: string;
};

export type GetCommentsByContentkeyUnapprovedResponse = (Array<(CommentSchema)>);

export type PatchCommentsByIdApproveData = {
    id: number;
};

export type PatchCommentsByIdApproveResponse = (boolean);

export type DeleteCommentsByIdDeleteData = {
    id: number;
};

export type DeleteCommentsByIdDeleteResponse = (boolean);

export type PatchCommentsByIdRestoreData = {
    id: number;
};

export type PatchCommentsByIdRestoreResponse = (boolean);

export type PatchCommentsByIdTrashData = {
    id: number;
};

export type PatchCommentsByIdTrashResponse = (boolean);

export type GetCommentsCountResponse = (number);

export type GetCommentsTrashedResponse = (Array<(CommentSchema)>);

export type GetCommentsTrashedCountResponse = (number);

export type GetCommentsUnapprovedResponse = (Array<(CommentSchema)>);

export type GetCommentsUnapprovedCountResponse = (number);