name: uDiscussions Release

env:
  CONFIGURATION: 'Release'
  OUTPUT: ./dist

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package version'
        required: true

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./Src/uDiscussions/uDiscussions.csproj
      
    - name: Build
      run: dotnet build ./Src/uDiscussions/uDiscussions.csproj --configuration ${{ env.CONFIGURATION }} --no-restore
      
    - name: Create NuGet package uDiscussions
      run: dotnet pack ./Src/uDiscussions/uDiscussions.csproj -c ${{ env.CONFIGURATION }} --no-build -o ${{ env.OUTPUT }} /p:version=${{ github.event.inputs.package_version }}
    
    - name: Create NuGet package uDiscussions.Client
      run: dotnet pack ./Src/uDiscussions.Client/uDiscussions.Client.csproj -c ${{ env.CONFIGURATION }} --no-build -o ${{ env.OUTPUT }} /p:version=${{ github.event.inputs.package_version }}
      
    - name: Create NuGet package uDiscussions.Core
      run: dotnet pack ./Src/uDiscussions.Core/uDiscussions.Core.csproj -c ${{ env.CONFIGURATION }} --no-build -o ${{ env.OUTPUT }} /p:version=${{ github.event.inputs.package_version }}

    - name: Upload NuGet package artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: uDiscussions-${{ github.event.inputs.package_version }}
        path: ${{ env.OUTPUT }}/**/*
  release:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/download-artifact@v4.2.1
        with:
          name: uDiscussions-${{ github.event.inputs.package_version }}
          path: ${{ env.OUTPUT }}
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Publish NuGet packages
        run: |
          foreach($file in (Get-ChildItem "${{ env.OUTPUT }}" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }